### ISSUE TITLE
I have tried your code but

### ISSUE THREAD

**Issue by SoftwareMagicIT** [christian-strydom/MauiForCars#1]
But in Android 13 app not available for Android Auto. I try also directly your project.

**Comment by christian-strydom** [comment]
Apologies for the delay. I just ran the sample again to confirm that it is still working on an Android 13 device and it is indeed still running as shown below:
![image](https://github.com/christian-strydom/MauiForCars/assets/62286796/6a986249-31ae-4abe-9305-dbd436165178)
![image](https://github.com/christian-strydom/MauiForCars/assets/62286796/2508edfd-65c9-4d3c-b433-82bc42f1581a)

Are you perhaps trying to run the app on your car without having deployed to the Google Play store internal track? 
https://youtu.be/nNkVxegb2oU?si=pG1ZdOAqYi5iep14&t=36
You can run the app in the desktop head emulator without publishing to store, but to run the app on a physical car you have to push it to the play store and download it from the play store. Please make sure you followed all the steps outlined in the video:
https://youtu.be/nNkVxegb2oU?si=pG1ZdOAqYi5iep14

**Comment by christian-strydom** [comment]
Closing this issue as I have not received a response in over a month.
